version: '3'

tasks:
  setup-qmk:
    cmds:
      - task: clone-qmk
      - task: pull-qmk

  clone-qmk:
    cmds:
      - git clone --recursive --single-branch git@github.com:qmk/qmk_firmware.git ../qmk_firmware
    status:
      - test -d ../qmk_firmware

  pull-qmk:
    cmds:
      - git -C ../qmk_firmware pull

  compile-all:
    deps: [build-lulu]

  compile-flash-lulu:
    cmds:
      - task: compile-lulu
      - task: flash-lulu

  compile-lulu:
    cmds:
      - |
        podman run --rm \
          -v ../qmk_firmware:/qmk_firmware:z \
          -v ./lulu/:/qmk_firmware/keyboards/boardsource/lulu/keymaps/tguimbert:z \
          -w /qmk_firmware \
          docker.io/qmkfm/qmk_cli \
          make boardsource/lulu/rp2040:tguimbert
      - mv ../qmk_firmware/boardsource_lulu_rp2040_tguimbert.uf2 .

  flash-lulu:
    cmds:
      - cp boardsource_lulu_rp2040_tguimbert.uf2 /run/media/$USER/RPI-RP2/
